### ISSUE TITLE
connection_table_to_matrix() function not working.

### ISSUE THREAD

**Issue by hannahj223** [connectome-neuprint/neuprint-python#50]
Hi there, 

I am new to neuprint-python and I was trying out the tutorial in a Jupyter notebook. However, when I am using the "connection_table_to_matrix()" function:

```python
from neuprint.utils import connection_table_to_matrix

matrix = connection_table_to_matrix(conn_df, 'bodyId', sort_by='type')
matrix.iloc[:10, :10]
```

I get the following error:

```pytb
TypeError                                 Traceback (most recent call last)
Cell In[11], line 3
      1 from neuprint.utils import connection_table_to_matrix
----> 3 matrix = connection_table_to_matrix(conn_df, 'bodyId', sort_by='type')
      4 matrix.iloc[:10, :10]

File ~\anaconda3\envs\my-conda-env\Lib\site-packages\neuprint\utils.py:304, in connection_table_to_matrix(conn_df, group_cols, weight_col, sort_by, make_square)
    301 dtype = conn_df[weight_col].dtype
    303 agg_weights_df = conn_df.groupby([col_pre, col_post], sort=False)[weight_col].sum().reset_index()
--> 304 matrix = agg_weights_df.pivot(col_pre, col_post, weight_col)
    305 matrix = matrix.fillna(0).astype(dtype)
    307 if sort_by:

TypeError: DataFrame.pivot() takes 1 positional argument but 4 were given
```

Does anyone know what the problem is here?

**Comment by stuarteberg** [comment]
Apologies; that's already been fixed in the git repo, but we haven't yet pushed out a new release with the fix.  I'll try to get to that soonish.

The issue is related to an API change in the `pandas`  library.  They changed the accepted arguments to the `pivot()` function.

If you don't want to wait for the new release, then you can edit the neuprint-python code on your own machine.

Open  `~\anaconda3\envs\my-conda-env\Lib\site-packages\neuprint\utils.py` and make the following change:

```diff
-    matrix = agg_weights_df.pivot(col_pre, col_post, weight_col)
+    matrix = agg_weights_df.pivot(index=col_pre, columns=col_post, values=weight_col)
```

(The relevant commit is [this one][1].)

[1]: https://github.com/connectome-neuprint/neuprint-python/commit/cab73b9e2e33c0133182769283cce7df7964bef7

**Comment by hannahj223** [comment]
That's great, I have made the change and this works. Thanks so much for your help :)
